#!/usr/bin/env Rscript
# =============================================================================
# Ne_estimation_LDmethod.R
# LD-based effective population size (Ne) estimation for GBS/RADseq data
#
# Species  : Cheirimedon femoratus (amphipod)
# Study    : Population genetics across South Shetland Islands
# Populations: DICF, KGCF, LICF, SICF
#
# Method   : Linkage disequilibrium (LD) method
#            Waples (2006) Mol Ecol 15:2607-2621
#            Hill (1981) Theor Pop Biol 19:117-128
#
# Input    : Per-population PED/MAP files (PLINK format)
#            Generated by 01_prepare_data.sh
#
# Output   : Ne_LDmethod_summary.csv  — Ne table (all populations, all Pcrit)
#            Ne_LDmethod_plot.pdf     — comparison plot with CI bars
#
# Usage    :
#   Rscript Ne_estimation_LDmethod.R
#   Rscript Ne_estimation_LDmethod.R --datadir /path/to/ne_data/populations
#                                     --outdir  /path/to/results
#
# Requirements:
#   R >= 4.0
#   install.packages(c("adegenet", "ggplot2", "dplyr"))
#
# Citation :
#   If you use this script, please cite:
#   Waples RS (2006) A bias correction for estimates of effective population
#     size based on linkage disequilibrium at unlinked gene loci.
#     Conservation Genetics 7:167-184.
# =============================================================================


# ── 0. Parse command-line arguments ──────────────────────────────────────────

args <- commandArgs(trailingOnly = TRUE)

get_arg <- function(flag, default) {
  idx <- which(args == flag)
  if (length(idx) > 0 && idx < length(args)) return(args[idx + 1])
  return(default)
}

DATADIR     <- get_arg("--datadir", "ne_data/populations")
OUTDIR      <- get_arg("--outdir",  "ne_results")
POPULATIONS <- c("DICF", "KGCF", "LICF", "SICF")
PCRITS      <- c(0.05, 0.02, 0.01)
MAX_SNPS    <- 2000    # max SNPs to subsample for speed; increase for more precision
MIN_PAIRS   <- 8       # min non-missing genotype pairs to calculate r2
N_BLOCKS    <- 200     # jackknife blocks for CI estimation
RANDOM_SEED <- 42

cat("=============================================================\n")
cat(" Ne estimation — LD method (Waples 2006)\n")
cat(" C. femoratus — South Shetland Islands\n")
cat("=============================================================\n")
cat(sprintf(" Data directory : %s\n", DATADIR))
cat(sprintf(" Output directory: %s\n", OUTDIR))
cat(sprintf(" Populations    : %s\n", paste(POPULATIONS, collapse=", ")))
cat(sprintf(" Pcrit values   : %s\n", paste(PCRITS, collapse=", ")))
cat(sprintf(" Max SNPs       : %d\n", MAX_SNPS))
cat("=============================================================\n\n")


# ── 1. Load required packages ─────────────────────────────────────────────────

required_pkgs <- c("adegenet", "ggplot2", "dplyr")
for (pkg in required_pkgs) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    stop(sprintf("Package '%s' is required. Install with: install.packages('%s')", pkg, pkg))
  }
}
suppressPackageStartupMessages({
  library(adegenet)
  library(ggplot2)
  library(dplyr)
})

dir.create(OUTDIR, recursive = TRUE, showWarnings = FALSE)


# ── 2. Read PED file and convert to numeric 0/1/2 genotype matrix ─────────────
#
# PLINK PED format:
#   Columns 1-6 : FID, IID, PID, MID, SEX, PHENOTYPE
#   Columns 7+  : two columns per SNP (allele1, allele2)
#   Missing     : coded as "0 0"
#
# Output matrix: individuals (rows) x SNPs (columns)
#   0 = homozygous major allele
#   1 = heterozygous
#   2 = homozygous minor allele
#   NA = missing

read_ped_numeric <- function(ped_file, map_file) {

  if (!file.exists(ped_file)) stop(sprintf("PED file not found: %s", ped_file))
  if (!file.exists(map_file)) stop(sprintf("MAP file not found: %s", map_file))

  ped <- read.table(ped_file, header = FALSE, stringsAsFactors = FALSE)
  map <- read.table(map_file, header = FALSE, stringsAsFactors = FALSE)

  n_ind    <- nrow(ped)
  n_snps   <- nrow(map)
  sample_ids <- ped[, 2]
  snp_ids    <- map[, 2]

  # Genotype columns start at column 7, two columns per SNP
  geno_cols <- seq(7, ncol(ped), by = 2)

  if (length(geno_cols) != n_snps) {
    warning(sprintf("Expected %d SNPs from MAP but found %d genotype column pairs in PED",
                    n_snps, length(geno_cols)))
    n_snps <- min(n_snps, length(geno_cols))
  }

  gmat <- matrix(NA_real_, nrow = n_ind, ncol = n_snps)

  for (j in seq_len(n_snps)) {
    col1 <- geno_cols[j]
    col2 <- col1 + 1
    a1   <- ped[, col1]
    a2   <- ped[, col2]

    # Identify missing genotypes (coded as "0" in PED)
    missing <- (a1 == "0") & (a2 == "0")

    # Identify alleles present in non-missing genotypes
    alleles <- c(a1[!missing], a2[!missing])
    if (length(alleles) == 0) next

    allele_counts <- table(alleles)
    if (length(allele_counts) < 2) next  # monomorphic — skip

    # Minor allele = least frequent allele
    minor_allele <- names(sort(allele_counts))[1]

    # Count copies of minor allele per individual (0, 1, or 2)
    counts           <- (a1 == minor_allele) + (a2 == minor_allele)
    counts[missing]  <- NA
    gmat[, j]        <- counts
  }

  rownames(gmat) <- sample_ids
  colnames(gmat) <- snp_ids[seq_len(n_snps)]

  missing_pct <- round(100 * sum(is.na(gmat)) / length(gmat), 1)
  cat(sprintf("  Loaded: %d individuals x %d SNPs | Missing data: %.1f%%\n",
              n_ind, n_snps, missing_pct))

  return(gmat)
}


# ── 3. LD-based Ne estimation (Waples 2006) ───────────────────────────────────
#
# Steps:
#   (a) Filter SNPs by minor allele frequency (Pcrit)
#   (b) Subsample SNPs if > MAX_SNPS (for computational speed)
#   (c) Calculate pairwise r² across all SNP pairs
#   (d) Apply Waples (2006) bias correction for sample size:
#         r²_drift = mean(r²) - 1/n - 3.19/n²
#   (e) Estimate Ne = 1 / (3 × r²_drift)
#   (f) 95% CI via block jackknife over SNP pairs
#
# Note: This implementation does not account for physical linkage between
# markers. For GBS/RADseq data with 1-3 SNPs per scaffold, this is
# acceptable as most pairs will be unlinked. For chromosome-scale assemblies,
# consider filtering to one SNP per locus before estimation.

calc_LDNe <- function(gmat, n_ind, Pcrit = 0.05,
                      max_snps = MAX_SNPS,
                      min_pairs = MIN_PAIRS,
                      n_blocks = N_BLOCKS,
                      seed = RANDOM_SEED) {

  # (a) Filter by minor allele frequency
  maf <- apply(gmat, 2, function(x) {
    x <- x[!is.na(x)]
    if (length(x) < min_pairs) return(NA)
    p <- mean(x) / 2
    min(p, 1 - p)
  })

  keep <- !is.na(maf) & maf >= Pcrit
  gmat_f <- gmat[, keep, drop = FALSE]
  p      <- ncol(gmat_f)

  cat(sprintf("    SNPs passing MAF >= %.2f: %d\n", Pcrit, p))

  if (p < 2) {
    cat("    Insufficient SNPs after MAF filter\n")
    return(list(Ne = NA, lower95CI = NA, upper95CI = NA,
                n_pairs = 0, mean_r2 = NA, r2_drift = NA))
  }

  # (b) Subsample SNPs for speed
  if (p > max_snps) {
    set.seed(seed)
    gmat_f <- gmat_f[, sample(p, max_snps), drop = FALSE]
    p      <- max_snps
    cat(sprintf("    Subsampled to %d SNPs (seed = %d)\n", p, seed))
  }

  # (c) Calculate pairwise r²
  n_total_pairs <- p * (p - 1) / 2
  cat(sprintf("    Calculating r² for %s SNP pairs...\n",
              format(n_total_pairs, big.mark = ",")))

  r2_vals <- numeric(0)

  for (i in 1:(p - 1)) {
    for (j in (i + 1):p) {
      x    <- gmat_f[, i]
      y    <- gmat_f[, j]
      keep_ij <- !is.na(x) & !is.na(y)

      # Skip pairs with too few observations or zero variance
      if (sum(keep_ij) < min_pairs) next
      if (var(x[keep_ij]) == 0 || var(y[keep_ij]) == 0) next

      r2 <- cor(x[keep_ij], y[keep_ij])^2
      if (!is.na(r2)) r2_vals <- c(r2_vals, r2)
    }
    if (i %% 200 == 0) {
      cat(sprintf("    Progress: %d / %d SNPs processed...\n", i, p))
    }
  }

  n_pairs <- length(r2_vals)
  cat(sprintf("    Valid r² pairs: %s\n", format(n_pairs, big.mark = ",")))

  if (n_pairs == 0) {
    cat("    No valid SNP pairs found\n")
    return(list(Ne = NA, lower95CI = NA, upper95CI = NA,
                n_pairs = 0, mean_r2 = NA, r2_drift = NA))
  }

  # (d) Waples (2006) bias correction
  mean_r2  <- mean(r2_vals)
  r2_drift <- mean_r2 - (1 / n_ind) - (3.19 / n_ind^2)

  cat(sprintf("    mean r²      = %.6f\n", mean_r2))
  cat(sprintf("    r²_drift     = %.6f  (after Waples 2006 correction)\n", r2_drift))

  # If r²_drift <= 0: Ne is effectively infinite (no detectable drift signal)
  if (is.na(r2_drift) || r2_drift <= 0) {
    cat("    r²_drift <= 0: Ne estimate = Inf (no drift signal detectable)\n")
    return(list(Ne = Inf, lower95CI = Inf, upper95CI = Inf,
                n_pairs = n_pairs, mean_r2 = mean_r2, r2_drift = r2_drift))
  }

  # (e) Point estimate
  Ne <- 1 / (3 * r2_drift)

  # (f) Block jackknife 95% CI
  n_blocks_used <- min(n_blocks, n_pairs)
  block_size    <- floor(n_pairs / n_blocks_used)

  jack_Ne <- sapply(seq_len(n_blocks_used), function(k) {
    idx  <- ((k - 1) * block_size + 1) : min(k * block_size, n_pairs)
    r2_k <- mean(r2_vals[-idx]) - (1 / n_ind) - (3.19 / n_ind^2)
    if (is.na(r2_k) || r2_k <= 0) return(NA)
    1 / (3 * r2_k)
  })

  se      <- sd(jack_Ne, na.rm = TRUE) * sqrt(n_blocks_used)
  ci_low  <- max(0, Ne - 1.96 * se)
  ci_high <- Ne + 1.96 * se

  return(list(
    Ne         = round(Ne, 1),
    lower95CI  = round(ci_low, 1),
    upper95CI  = round(ci_high, 1),
    n_pairs    = n_pairs,
    mean_r2    = round(mean_r2, 6),
    r2_drift   = round(r2_drift, 6)
  ))
}


# ── 4. Run Ne estimation for all populations and Pcrit values ─────────────────

results <- data.frame()

for (pop in POPULATIONS) {

  ped_file <- file.path(DATADIR, pop, paste0(pop, ".ped"))
  map_file <- file.path(DATADIR, pop, paste0(pop, ".map"))

  cat(sprintf("\n── %s ──────────────────────────────────────\n", pop))

  # Check files exist
  if (!file.exists(ped_file)) {
    cat(sprintf("  SKIP: PED file not found: %s\n", ped_file))
    next
  }

  # Read genotype matrix
  gmat  <- read_ped_numeric(ped_file, map_file)
  n_ind <- nrow(gmat)

  # Run at each Pcrit threshold
  for (pc in PCRITS) {

    cat(sprintf("\n  Pcrit = %.2f\n", pc))

    res <- tryCatch(
      calc_LDNe(gmat, n_ind, Pcrit = pc),
      error = function(e) {
        cat(sprintf("  ERROR: %s\n", e$message))
        list(Ne = NA, lower95CI = NA, upper95CI = NA,
             n_pairs = 0, mean_r2 = NA, r2_drift = NA)
      }
    )

    cat(sprintf("  >>> Ne = %s  (95%% CI: %s – %s)\n",
                res$Ne, res$lower95CI, res$upper95CI))

    results <- rbind(results, data.frame(
      Population = pop,
      N_ind      = n_ind,
      Pcrit      = pc,
      Ne         = res$Ne,
      CI_low     = res$lower95CI,
      CI_high    = res$upper95CI,
      N_pairs    = res$n_pairs,
      mean_r2    = res$mean_r2,
      r2_drift   = res$r2_drift,
      stringsAsFactors = FALSE
    ))
  }
}


# ── 5. Print and save summary table ───────────────────────────────────────────

cat("\n=============================================================\n")
cat(" Ne Summary — C. femoratus — LD method (Waples 2006)\n")
cat("=============================================================\n")
print(results[, c("Population", "N_ind", "Pcrit", "Ne", "CI_low", "CI_high")])

outfile <- file.path(OUTDIR, "Ne_LDmethod_summary.csv")
write.csv(results, outfile, row.names = FALSE)
cat(sprintf("\nFull results saved to: %s\n", outfile))


# ── 6. Publication-ready comparison plot ──────────────────────────────────────

# Use Pcrit = 0.05 as primary estimate for plot
# Flag infinite Ne estimates (no drift signal detectable)

plot_data <- results %>%
  filter(Pcrit == 0.05) %>%
  mutate(
    Population = factor(Population, levels = POPULATIONS),
    Ne_plot    = ifelse(is.infinite(Ne), NA, Ne),
    CI_low_plot  = ifelse(is.infinite(CI_low),  NA, CI_low),
    CI_high_plot = ifelse(is.infinite(CI_high), NA, CI_high),
    label      = ifelse(is.infinite(Ne), "Inf", as.character(Ne))
  )

pop_colors <- c(
  DICF = "#1D9E75",
  KGCF = "#378ADD",
  LICF = "#7F77DD",
  SICF = "#D85A30"
)

p <- ggplot(plot_data, aes(x = Population, y = Ne_plot, color = Population)) +
  geom_point(size = 4) +
  geom_errorbar(aes(ymin = CI_low_plot, ymax = CI_high_plot),
                width = 0.2, linewidth = 0.9) +
  scale_color_manual(values = pop_colors) +
  scale_y_continuous(labels = scales::comma, limits = c(0, NA)) +
  labs(
    title    = expression(paste("Effective population size (", italic("N")[e], ") — ", italic("C. femoratus"))),
    subtitle = "LD method (Waples 2006) | Pcrit = 0.05 | Jackknife 95% CI",
    x        = "Population",
    y        = expression(italic("N")[e]),
    caption  = paste0("Note: KGCF CI is wide due to small sample size (n = ",
                      plot_data$N_ind[plot_data$Population == "KGCF"], "). ",
                      "Infinite estimates not shown.")
  ) +
  theme_classic(base_size = 13) +
  theme(
    legend.position    = "none",
    panel.grid.major.y = element_line(color = "grey92"),
    plot.title         = element_text(face = "bold"),
    plot.subtitle      = element_text(color = "grey40")
  )

plot_file <- file.path(OUTDIR, "Ne_LDmethod_plot.pdf")
ggsave(plot_file, p, width = 6, height = 5)
cat(sprintf("Plot saved to: %s\n", plot_file))

# Also save sensitivity plot (all Pcrit values)
sens_data <- results %>%
  filter(is.finite(Ne)) %>%
  mutate(
    Population = factor(Population, levels = POPULATIONS),
    Pcrit_label = paste0("Pcrit = ", Pcrit)
  )

if (nrow(sens_data) > 0) {
  p_sens <- ggplot(sens_data, aes(x = Population, y = Ne, color = Population)) +
    geom_point(size = 3) +
    geom_errorbar(aes(ymin = CI_low, ymax = CI_high),
                  width = 0.2, linewidth = 0.8) +
    facet_wrap(~Pcrit_label, scales = "free_y") +
    scale_color_manual(values = pop_colors) +
    scale_y_continuous(labels = scales::comma) +
    labs(
      title    = expression(paste(italic("N")[e], " sensitivity to Pcrit threshold")),
      subtitle = "LD method (Waples 2006) | Jackknife 95% CI",
      x = NULL, y = expression(italic("N")[e])
    ) +
    theme_classic(base_size = 12) +
    theme(
      legend.position    = "none",
      strip.background   = element_blank(),
      strip.text         = element_text(face = "bold"),
      panel.grid.major.y = element_line(color = "grey92")
    )

  sens_file <- file.path(OUTDIR, "Ne_LDmethod_sensitivity.pdf")
  ggsave(sens_file, p_sens, width = 9, height = 4)
  cat(sprintf("Sensitivity plot saved to: %s\n", sens_file))
}

cat("\n=============================================================\n")
cat(" Done. Output files:\n")
cat(sprintf("   %s\n", outfile))
cat(sprintf("   %s\n", plot_file))
if (nrow(sens_data) > 0) cat(sprintf("   %s\n", sens_file))
cat("=============================================================\n")
